export const sevenDays = [
  {
    time: '00:00',
    id: Math.random(),
    monday: "-",
    tuesday: "-",
    wendesday: "-",
    thursday: "-",
    friday: "-",
    saturday: "-",
    sunday: "-",
  },
  {
    time: '01:00',
    id: Math.random(),
    monday: "-",
    tuesday: "-",
    wendesday: "-",
    thursday: "-",
    friday: "-",
    saturday: "-",
    sunday: "-",
  },
  {
    time: '02:00',
    id: Math.random(),
    monday: "-",
    tuesday: "-",
    wendesday: "-",
    thursday: "-",
    friday: "-",
    saturday: "-",
    sunday: "-",
  },
  {
    time: '03:00',
    id: Math.random(),
    monday: "-",
    tuesday: "-",
    wendesday: "-",
    thursday: "-",
    friday: "-",
    saturday: "-",
    sunday: "-",
  },
  {
    time: '04:00',
    id: Math.random(),
    monday: "-",
    tuesday: "-",
    wendesday: "-",
    thursday: "-",
    friday: "-",
    saturday: "-",
    sunday: "-",
  },
  {
    time: '05:00',
    id: Math.random(),
    monday: "-",
    tuesday: "-",
    wendesday: "-",
    thursday: "-",
    friday: "-",
    saturday: "-",
    sunday: "-",
  },
  {
    time: '06:00',
    id: Math.random(),
    monday: "-",
    tuesday: "-",
    wendesday: "-",
    thursday: "-",
    friday: "-",
    saturday: "-",
    sunday: "-",
  },
  {
    time: '07:00',
    id: Math.random(),
    monday: "-",
    tuesday: "-",
    wendesday: "-",
    thursday: "-",
    friday: "-",
    saturday: "-",
    sunday: "-",
  },
  {
    time: '08:00',
    id: Math.random(),
    monday: "-",
    tuesday: "-",
    wendesday: "-",
    thursday: "-",
    friday: "-",
    saturday: "-",
    sunday: "-",
  },
  {
    time: '09:00',
    id: Math.random(),
    monday: "-",
    tuesday: "-",
    wendesday: "-",
    thursday: "-",
    friday: "-",
    saturday: "-",
    sunday: "-",
  },
  {
    time: '10:00',
    id: Math.random(),
    monday: "-",
    tuesday: "-",
    wendesday: "-",
    thursday: "-",
    friday: "-",
    saturday: "-",
    sunday: "-",
  },
  {
    time: '11:00',
    id: Math.random(),
    monday: "-",
    tuesday: "-",
    wendesday: "-",
    thursday: "-",
    friday: "-",
    saturday: "-",
    sunday: "-",
  },
  {
    time: '12:00',
    id: Math.random(),
    monday: "-",
    tuesday: "-",
    wendesday: "-",
    thursday: "-",
    friday: "-",
    saturday: "-",
    sunday: "-",
  },
  {
    time: '13:00',
    id: Math.random(),
    monday: "-",
    tuesday: "-",
    wendesday: "-",
    thursday: "-",
    friday: "-",
    saturday: "-",
    sunday: "-",
  },
  {
    time: '14:00',
    id: Math.random(),
    monday: "-",
    tuesday: "-",
    wendesday: "-",
    thursday: "-",
    friday: "-",
    saturday: "-",
    sunday: "-",
  },
  {
    time: '15:00',
    id: Math.random(),
    monday: "-",
    tuesday: "-",
    wendesday: "-",
    thursday: "-",
    friday: "-",
    saturday: "-",
    sunday: "-",
  },
  {
    time: '16:00',
    id: Math.random(),
    monday: "-",
    tuesday: "-",
    wendesday: "-",
    thursday: "-",
    friday: "-",
    saturday: "-",
    sunday: "-",
  },
  {
    time: '17:00',
    id: Math.random(),
    monday: "-",
    tuesday: "-",
    wendesday: "-",
    thursday: "-",
    friday: "-",
    saturday: "-",
    sunday: "-",
  },
  {
    time: '18:00',
    id: Math.random(),
    monday: "-",
    tuesday: "-",
    wendesday: "-",
    thursday: "-",
    friday: "-",
    saturday: "-",
    sunday: "-",
  },
  {
    time: '19:00',
    id: Math.random(),
    monday: "-",
    tuesday: "-",
    wendesday: "-",
    thursday: "-",
    friday: "-",
    saturday: "-",
    sunday: "-",
  },
  {
    time: '20:00',
    id: Math.random(),
    monday: "-",
    tuesday: "-",
    wendesday: "-",
    thursday: "-",
    friday: "-",
    saturday: "-",
    sunday: "-",
  },
  {
    time: '21:00',
    id: Math.random(),
    monday: "-",
    tuesday: "-",
    wendesday: "-",
    thursday: "-",
    friday: "-",
    saturday: "-",
    sunday: "-",
  },
  {
    time: '22:00',
    id: Math.random(),
    monday: "-",
    tuesday: "-",
    wendesday: "-",
    thursday: "-",
    friday: "-",
    saturday: "-",
    sunday: "-",
  },
  {
    time: '23:00',
    id: Math.random(),
    monday: "-",
    tuesday: "-",
    wendesday: "-",
    thursday: "-",
    friday: "-",
    saturday: "-",
    sunday: "-",
  },
];
