const sevenDays = [
  {
    time: '00:00',
    id: 0,
    monday: {
      id: Math.random(),
      message: '',
      day: 'Monday',
      parenTime: '00:00',
    },
    tuesday: {
      id: Math.random(),
      message: '',
      day: 'Tuesday',
      parenTime: '00:00',
    },
    wendesday: {
      id: Math.random(),
      message: '',
      day: 'Wendesday',
      parenTime: '00:00',
    },
    thursday: {
      id: Math.random(),
      message: '',
      day: 'Thursday',
      parenTime: '00:00',
    },
    friday: {
      id: Math.random(),
      message: '',
      day: 'Friday',
      parenTime: '00:00',
    },
    saturday: {
      id: Math.random(),
      message: '',
      day: 'Saturday',
      parenTime: '00:00',
    },
    sunday: {
      id: Math.random(),
      message: '',
      day: 'Sunday',
      parenTime: '00:00',
    },
  },
  {
    time: '01:00',
    id: 1,
    monday: {
      id: Math.random(),
      message: '',
      day: 'Monday',
      parenTime: '01:00',
    },
    tuesday: {
      id: Math.random(),
      message: '',
      day: 'Tuesday',
      parenTime: '01:00',
    },
    wendesday: {
      id: Math.random(),
      message: '',
      day: 'Wendesday',
      parenTime: '01:00',
    },
    thursday: {
      id: Math.random(),
      message: '',
      day: 'Thursday',
      parenTime: '01:00',
    },
    friday: {
      id: Math.random(),
      message: '',
      day: 'Friday',
      parenTime: '01:00',
    },
    saturday: {
      id: Math.random(),
      message: '',
      day: 'Saturday',
      parenTime: '01:00',
    },
    sunday: {
      id: Math.random(),
      message: '',
      day: 'Sunday',
      parenTime: '01:00',
    },
  },
  {
    time: '02:00',
    id: 2,
    monday: {
      id: Math.random(),
      message: '',
      day: 'Monday',
      parenTime: '02:00',
    },
    tuesday: {
      id: Math.random(),
      message: '',
      day: 'Tuesday',
      parenTime: '02:00',
    },
    wendesday: {
      id: Math.random(),
      message: '',
      day: 'Wendesday',
      parenTime: '02:00',
    },
    thursday: {
      id: Math.random(),
      message: '',
      day: 'Thursday',
      parenTime: '02:00',
    },
    friday: {
      id: Math.random(),
      message: '',
      day: 'Friday',
      parenTime: '02:00',
    },
    saturday: {
      id: Math.random(),
      message: '',
      day: 'Saturday',
      parenTime: '02:00',
    },
    sunday: {
      id: Math.random(),
      message: '',
      day: 'Sunday',
      parenTime: '02:00',
    },
  },
  {
    time: '03:00',
    id: 3,
    monday: {
      id: Math.random(),
      message: '',
      day: 'Monday',
      parenTime: '03:00',
    },
    tuesday: {
      id: Math.random(),
      message: '',
      day: 'Tuesday',
      parenTime: '03:00',
    },
    wendesday: {
      id: Math.random(),
      message: '',
      day: 'Wendesday',
      parenTime: '03:00',
    },
    thursday: {
      id: Math.random(),
      message: '',
      day: 'Thursday',
      parenTime: '03:00',
    },
    friday: {
      id: Math.random(),
      message: '',
      day: 'Friday',
      parenTime: '03:00',
    },
    saturday: {
      id: Math.random(),
      message: '',
      day: 'Saturday',
      parenTime: '03:00',
    },
    sunday: {
      id: Math.random(),
      message: '',
      day: 'Sunday',
      parenTime: '03:00',
    },
  },
  {
    time: '04:00',
    id: 4,
    monday: {
      id: Math.random(),
      message: '',
      day: 'Monday',
      parenTime: '04:00',
    },
    tuesday: {
      id: Math.random(),
      message: '',
      day: 'Tuesday',
      parenTime: '04:00',
    },
    wendesday: {
      id: Math.random(),
      message: '',
      day: 'Wendesday',
      parenTime: '04:00',
    },
    thursday: {
      id: Math.random(),
      message: '',
      day: 'Thursday',
      parenTime: '04:00',
    },
    friday: {
      id: Math.random(),
      message: '',
      day: 'Friday',
      parenTime: '04:00',
    },
    saturday: {
      id: Math.random(),
      message: '',
      day: 'Saturday',
      parenTime: '04:00',
    },
    sunday: {
      id: Math.random(),
      message: '',
      day: 'Sunday',
      parenTime: '04:00',
    },
  },
  {
    time: '05:00',
    id: 5,
    monday: {
      id: Math.random(),
      message: '',
      day: 'Monday',
      parenTime: '05:00',
    },
    tuesday: {
      id: Math.random(),
      message: '',
      day: 'Tuesday',
      parenTime: '05:00',
    },
    wendesday: {
      id: Math.random(),
      message: '',
      day: 'Wendesday',
      parenTime: '05:00',
    },
    thursday: {
      id: Math.random(),
      message: '',
      day: 'Thursday',
      parenTime: '05:00',
    },
    friday: {
      id: Math.random(),
      message: '',
      day: 'Friday',
      parenTime: '05:00',
    },
    saturday: {
      id: Math.random(),
      message: '',
      day: 'Saturday',
      parenTime: '05:00',
    },
    sunday: {
      id: Math.random(),
      message: '',
      day: 'Sunday',
      parenTime: '05:00',
    },
  },
  {
    time: '06:00',
    id: 6,
    monday: {
      id: Math.random(),
      message: '',
      day: 'Monday',
      parenTime: '06:00',
    },
    tuesday: {
      id: Math.random(),
      message: '',
      day: 'Tuesday',
      parenTime: '06:00',
    },
    wendesday: {
      id: Math.random(),
      message: '',
      day: 'Wendesday',
      parenTime: '06:00',
    },
    thursday: {
      id: Math.random(),
      message: '',
      day: 'Thursday',
      parenTime: '06:00',
    },
    friday: {
      id: Math.random(),
      message: '',
      day: 'Friday',
      parenTime: '06:00',
    },
    saturday: {
      id: Math.random(),
      message: '',
      day: 'Saturday',
      parenTime: '06:00',
    },
    sunday: {
      id: Math.random(),
      message: '',
      day: 'Sunday',
      parenTime: '06:00',
    },
  },
  {
    time: '07:00',
    id: 7,
    monday: {
      id: Math.random(),
      message: '',
      day: 'Monday',
      parenTime: '07:00',
    },
    tuesday: {
      id: Math.random(),
      message: '',
      day: 'Tuesday',
      parenTime: '07:00',
    },
    wendesday: {
      id: Math.random(),
      message: '',
      day: 'Wendesday',
      parenTime: '07:00',
    },
    thursday: {
      id: Math.random(),
      message: '',
      day: 'Thursday',
      parenTime: '07:00',
    },
    friday: {
      id: Math.random(),
      message: '',
      day: 'Friday',
      parenTime: '07:00',
    },
    saturday: {
      id: Math.random(),
      message: '',
      day: 'Saturday',
      parenTime: '07:00',
    },
    sunday: {
      id: Math.random(),
      message: '',
      day: 'Sunday',
      parenTime: '07:00',
    },
  },
  {
    time: '08:00',
    id: 8,
    monday: {
      id: Math.random(),
      message: '',
      day: 'Monday',
      parenTime: '08:00',
    },
    tuesday: {
      id: Math.random(),
      message: '',
      day: 'Tuesday',
      parenTime: '08:00',
    },
    wendesday: {
      id: Math.random(),
      message: '',
      day: 'Wendesday',
      parenTime: '08:00',
    },
    thursday: {
      id: Math.random(),
      message: '',
      day: 'Thursday',
      parenTime: '08:00',
    },
    friday: {
      id: Math.random(),
      message: '',
      day: 'Friday',
      parenTime: '08:00',
    },
    saturday: {
      id: Math.random(),
      message: '',
      day: 'Saturday',
      parenTime: '08:00',
    },
    sunday: {
      id: Math.random(),
      message: '',
      day: 'Sunday',
      parenTime: '08:00',
    },
  },
  {
    time: '09:00',
    id: 9,
    monday: {
      id: Math.random(),
      message: '',
      day: 'Monday',
      parenTime: '09:00',
    },
    tuesday: {
      id: Math.random(),
      message: '',
      day: 'Tuesday',
      parenTime: '09:00',
    },
    wendesday: {
      id: Math.random(),
      message: '',
      day: 'Wendesday',
      parenTime: '09:00',
    },
    thursday: {
      id: Math.random(),
      message: '',
      day: 'Thursday',
      parenTime: '09:00',
    },
    friday: {
      id: Math.random(),
      message: '',
      day: 'Friday',
      parenTime: '09:00',
    },
    saturday: {
      id: Math.random(),
      message: '',
      day: 'Saturday',
      parenTime: '09:00',
    },
    sunday: {
      id: Math.random(),
      message: '',
      day: 'Sunday',
      parenTime: '09:00',
    },
  },
  {
    time: '10:00',
    id: 10,
    monday: {
      id: Math.random(),
      message: '',
      day: 'Monday',
      parenTime: '10:00',
    },
    tuesday: {
      id: Math.random(),
      message: '',
      day: 'Tuesday',
      parenTime: '10:00',
    },
    wendesday: {
      id: Math.random(),
      message: '',
      day: 'Wendesday',
      parenTime: '10:00',
    },
    thursday: {
      id: Math.random(),
      message: '',
      day: 'Thursday',
      parenTime: '10:00',
    },
    friday: {
      id: Math.random(),
      message: '',
      day: 'Friday',
      parenTime: '10:00',
    },
    saturday: {
      id: Math.random(),
      message: '',
      day: 'Saturday',
      parenTime: '10:00',
    },
    sunday: {
      id: Math.random(),
      message: '',
      day: 'Sunday',
      parenTime: '10:00',
    },
  },
  {
    time: '11:00',
    id: 11,
    monday: {
      id: Math.random(),
      message: '',
      day: 'Monday',
      parenTime: '11:00',
    },
    tuesday: {
      id: Math.random(),
      message: '',
      day: 'Tuesday',
      parenTime: '11:00',
    },
    wendesday: {
      id: Math.random(),
      message: '',
      day: 'Wendesday',
      parenTime: '11:00',
    },
    thursday: {
      id: Math.random(),
      message: '',
      day: 'Thursday',
      parenTime: '11:00',
    },
    friday: {
      id: Math.random(),
      message: '',
      day: 'Friday',
      parenTime: '11:00',
    },
    saturday: {
      id: Math.random(),
      message: '',
      day: 'Saturday',
      parenTime: '11:00',
    },
    sunday: {
      id: Math.random(),
      message: '',
      day: 'Sunday',
      parenTime: '11:00',
    },
  },
  {
    time: '12:00',
    id: 12,
    monday: {
      id: Math.random(),
      message: '',
      day: 'Monday',
      parenTime: '12:00',
    },
    tuesday: {
      id: Math.random(),
      message: '',
      day: 'Tuesday',
      parenTime: '12:00',
    },
    wendesday: {
      id: Math.random(),
      message: '',
      day: 'Wendesday',
      parenTime: '12:00',
    },
    thursday: {
      id: Math.random(),
      message: '',
      day: 'Thursday',
      parenTime: '12:00',
    },
    friday: {
      id: Math.random(),
      message: '',
      day: 'Friday',
      parenTime: '12:00',
    },
    saturday: {
      id: Math.random(),
      message: '',
      day: 'Saturday',
      parenTime: '12:00',
    },
    sunday: {
      id: Math.random(),
      message: '',
      day: 'Sunday',
      parenTime: '12:00',
    },
  },
  {
    time: '13:00',
    id: 13,
    monday: {
      id: Math.random(),
      message: '',
      day: 'Monday',
      parenTime: '13:00',
    },
    tuesday: {
      id: Math.random(),
      message: '',
      day: 'Tuesday',
      parenTime: '13:00',
    },
    wendesday: {
      id: Math.random(),
      message: '',
      day: 'Wendesday',
      parenTime: '13:00',
    },
    thursday: {
      id: Math.random(),
      message: '',
      day: 'Thursday',
      parenTime: '13:00',
    },
    friday: {
      id: Math.random(),
      message: '',
      day: 'Friday',
      parenTime: '13:00',
    },
    saturday: {
      id: Math.random(),
      message: '',
      day: 'Saturday',
      parenTime: '13:00',
    },
    sunday: {
      id: Math.random(),
      message: '',
      day: 'Sunday',
      parenTime: '13:00',
    },
  },
  {
    time: '14:00',
    id: 14,
    monday: {
      id: Math.random(),
      message: '',
      day: 'Monday',
      parenTime: '14:00',
    },
    tuesday: {
      id: Math.random(),
      message: '',
      day: 'Tuesday',
      parenTime: '14:00',
    },
    wendesday: {
      id: Math.random(),
      message: '',
      day: 'Wendesday',
      parenTime: '14:00',
    },
    thursday: {
      id: Math.random(),
      message: '',
      day: 'Thursday',
      parenTime: '14:00',
    },
    friday: {
      id: Math.random(),
      message: '',
      day: 'Friday',
      parenTime: '14:00',
    },
    saturday: {
      id: Math.random(),
      message: '',
      day: 'Saturday',
      parenTime: '14:00',
    },
    sunday: {
      id: Math.random(),
      message: '',
      day: 'Sunday',
      parenTime: '14:00',
    },
  },
  {
    time: '15:00',
    id: 15,
    monday: {
      id: Math.random(),
      message: '',
      day: 'Monday',
      parenTime: '15:00',
    },
    tuesday: {
      id: Math.random(),
      message: '',
      day: 'Tuesday',
      parenTime: '15:00',
    },
    wendesday: {
      id: Math.random(),
      message: '',
      day: 'Wendesday',
      parenTime: '15:00',
    },
    thursday: {
      id: Math.random(),
      message: '',
      day: 'Thursday',
      parenTime: '15:00',
    },
    friday: {
      id: Math.random(),
      message: '',
      day: 'Friday',
      parenTime: '15:00',
    },
    saturday: {
      id: Math.random(),
      message: '',
      day: 'Saturday',
      parenTime: '15:00',
    },
    sunday: {
      id: Math.random(),
      message: '',
      day: 'Sunday',
      parenTime: '15:00',
    },
  },
  {
    time: '16:00',
    id: 16,
    monday: {
      id: Math.random(),
      message: '',
      day: 'Monday',
      parenTime: '16:00',
    },
    tuesday: {
      id: Math.random(),
      message: '',
      day: 'Tuesday',
      parenTime: '16:00',
    },
    wendesday: {
      id: Math.random(),
      message: '',
      day: 'Wendesday',
      parenTime: '16:00',
    },
    thursday: {
      id: Math.random(),
      message: '',
      day: 'Thursday',
      parenTime: '16:00',
    },
    friday: {
      id: Math.random(),
      message: '',
      day: 'Friday',
      parenTime: '16:00',
    },
    saturday: {
      id: Math.random(),
      message: '',
      day: 'Saturday',
      parenTime: '16:00',
    },
    sunday: {
      id: Math.random(),
      message: '',
      day: 'Sunday',
      parenTime: '16:00',
    },
  },
  {
    time: '17:00',
    id: 17,
    monday: {
      id: Math.random(),
      message: '',
      day: 'Monday',
      parenTime: '17:00',
    },
    tuesday: {
      id: Math.random(),
      message: '',
      day: 'Tuesday',
      parenTime: '17:00',
    },
    wendesday: {
      id: Math.random(),
      message: '',
      day: 'Wendesday',
      parenTime: '17:00',
    },
    thursday: {
      id: Math.random(),
      message: '',
      day: 'Thursday',
      parenTime: '17:00',
    },
    friday: {
      id: Math.random(),
      message: '',
      day: 'Friday',
      parenTime: '17:00',
    },
    saturday: {
      id: Math.random(),
      message: '',
      day: 'Saturday',
      parenTime: '17:00',
    },
    sunday: {
      id: Math.random(),
      message: '',
      day: 'Sunday',
      parenTime: '17:00',
    },
  },
  {
    time: '18:00',
    id: 18,
    monday: {
      id: Math.random(),
      message: '',
      day: 'Monday',
      parenTime: '18:00',
    },
    tuesday: {
      id: Math.random(),
      message: '',
      day: 'Tuesday',
      parenTime: '18:00',
    },
    wendesday: {
      id: Math.random(),
      message: '',
      day: 'Wendesday',
      parenTime: '18:00',
    },
    thursday: {
      id: Math.random(),
      message: '',
      day: 'Thursday',
      parenTime: '18:00',
    },
    friday: {
      id: Math.random(),
      message: '',
      day: 'Friday',
      parenTime: '18:00',
    },
    saturday: {
      id: Math.random(),
      message: '',
      day: 'Saturday',
      parenTime: '18:00',
    },
    sunday: {
      id: Math.random(),
      message: '',
      day: 'Sunday',
      parenTime: '18:00',
    },
  },
  {
    time: '19:00',
    id: 19,
    monday: {
      id: Math.random(),
      message: '',
      day: 'Monday',
      parenTime: '19:00',
    },
    tuesday: {
      id: Math.random(),
      message: '',
      day: 'Tuesday',
      parenTime: '19:00',
    },
    wendesday: {
      id: Math.random(),
      message: '',
      day: 'Wendesday',
      parenTime: '19:00',
    },
    thursday: {
      id: Math.random(),
      message: '',
      day: 'Thursday',
      parenTime: '19:00',
    },
    friday: {
      id: Math.random(),
      message: '',
      day: 'Friday',
      parenTime: '19:00',
    },
    saturday: {
      id: Math.random(),
      message: '',
      day: 'Saturday',
      parenTime: '19:00',
    },
    sunday: {
      id: Math.random(),
      message: '',
      day: 'Sunday',
      parenTime: '19:00',
    },
  },
  {
    time: '20:00',
    id: 20,
    monday: {
      id: Math.random(),
      message: '',
      day: 'Monday',
      parenTime: '20:00',
    },
    tuesday: {
      id: Math.random(),
      message: '',
      day: 'Tuesday',
      parenTime: '20:00',
    },
    wendesday: {
      id: Math.random(),
      message: '',
      day: 'Wendesday',
      parenTime: '20:00',
    },
    thursday: {
      id: Math.random(),
      message: '',
      day: 'Thursday',
      parenTime: '20:00',
    },
    friday: {
      id: Math.random(),
      message: '',
      day: 'Friday',
      parenTime: '20:00',
    },
    saturday: {
      id: Math.random(),
      message: '',
      day: 'Saturday',
      parenTime: '20:00',
    },
    sunday: {
      id: Math.random(),
      message: '',
      day: 'Sunday',
      parenTime: '20:00',
    },
  },
  {
    time: '21:00',
    id: 21,
    monday: {
      id: Math.random(),
      message: '',
      day: 'Monday',
      parenTime: '21:00',
    },
    tuesday: {
      id: Math.random(),
      message: '',
      day: 'Tuesday',
      parenTime: '21:00',
    },
    wendesday: {
      id: Math.random(),
      message: '',
      day: 'Wendesday',
      parenTime: '21:00',
    },
    thursday: {
      id: Math.random(),
      message: '',
      day: 'Thursday',
      parenTime: '21:00',
    },
    friday: {
      id: Math.random(),
      message: '',
      day: 'Friday',
      parenTime: '21:00',
    },
    saturday: {
      id: Math.random(),
      message: '',
      day: 'Saturday',
      parenTime: '21:00',
    },
    sunday: {
      id: Math.random(),
      message: '',
      day: 'Sunday',
      parenTime: '21:00',
    },
  },
  {
    time: '22:00',
    id: 22,
    monday: {
      id: Math.random(),
      message: '',
      day: 'Monday',
      parenTime: '22:00',
    },
    tuesday: {
      id: Math.random(),
      message: '',
      day: 'Tuesday',
      parenTime: '22:00',
    },
    wendesday: {
      id: Math.random(),
      message: '',
      day: 'Wendesday',
      parenTime: '22:00',
    },
    thursday: {
      id: Math.random(),
      message: '',
      day: 'Thursday',
      parenTime: '22:00',
    },
    friday: {
      id: Math.random(),
      message: '',
      day: 'Friday',
      parenTime: '22:00',
    },
    saturday: {
      id: Math.random(),
      message: '',
      day: 'Saturday',
      parenTime: '22:00',
    },
    sunday: {
      id: Math.random(),
      message: '',
      day: 'Sunday',
      parenTime: '22:00',
    },
  },
  {
    time: '23:00',
    id: 23,
    monday: {
      id: Math.random(),
      message: '',
      day: 'Monday',
      parenTime: '23:00',
    },
    tuesday: {
      id: Math.random(),
      message: '',
      day: 'Tuesday',
      parenTime: '23:00',
    },
    wendesday: {
      id: Math.random(),
      message: '',
      day: 'Wendesday',
      parenTime: '23:00',
    },
    thursday: {
      id: Math.random(),
      message: '',
      day: 'Thursday',
      parenTime: '23:00',
    },
    friday: {
      id: Math.random(),
      message: '',
      day: 'Friday',
      parenTime: '23:00',
    },
    saturday: {
      id: Math.random(),
      message: '',
      day: 'Saturday',
      parenTime: '23:00',
    },
    sunday: {
      id: Math.random(),
      message: '',
      day: 'Sunday',
      parenTime: '23:00',
    },
  },
];

module.exports = sevenDays;
